name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test folder
      uses: datalbry/copy_folder_to_another_repo_action@1.0.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_folder: 'dist/'
        destination_repo: 'herbertnikolajewskidci/kursUebersichtWebDev.github.io'
        destination_folder: 'dist/'
        user_email: 'herbert.nikolajewski@digitalcareerinstitute.org'
        user_name: 'herbertnikolajewskidci'
        commit_msg: '[GHA] Update the test files.'
